[project]
name = "daniel-blog-air"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air>=0.11.0",
    "python-dateutil>=2.9.0.post0",
    "pytz>=2025.2",
]
